[general]
enable_bucket = true                        # 是否使用Aspect Ratio Bucketing

[[datasets]]
resolution = [384, 320]                            # 训练分辨率
batch_size = 8                              # 批次大小

  [[datasets.subsets]]
  image_dir = '/fastdata/datasets/fler/train'                     # 指定包含训练图像的文件夹
  caption_extension = '.txt'            # 若使用txt文件,更改此项
  num_repeats = 1                       # 训练图像的重复次数
